######################################################
################## ACTOR REQUESTS ####################
######################################################
#####
GET http://localhost:3000/actors.json

#####
GET http://localhost:3000/actors/2.json

#####
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "christan",
  "last_name": "bale",
  "known_for": "batman"
}

#####
PATCH http://localhost:3000/actors/26.json
Content-Type: application/json

{
  "first_name": "clark",
  "last_name": "kent",
  "known_for": "superman"
}

#####
DELETE http://localhost:3000/actors/26.json


######################################################
################## MOVIES REQUESTS ###################
######################################################
#####
GET http://localhost:3000/movies.json

#####
GET http://localhost:3000/movies/2.json

#####
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "The Godfather",
  "year": "1972",
  "plot": "The aging patriarch of an organized crime dynasty in postwar New York City transfers control of his clandestine empire to his reluctant youngest son."
}

#####
PATCH http://localhost:3000/movies/2.json
Content-Type: application/json

{
  "title": "Breakfast at Tiffany's",
  "year": "1961",
  "plot": "A young New York socialite becomes interested in a young man who has moved into her apartment building, but her past threatens to get in the way."
}

#####
DELETE http://localhost:3000/movies/8

