
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NTgyNTgyNzN9.uiA3XevWVgDb6wTcsohkQ1RVD8m0--DcYG8RGrpXsgo

######### CREATE NEW #########
POST http://localhost:3000/sessions.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "email": "ringo@example.com",
  "password": "password"
}


##### DELETE #####
DELETE http://localhost:3000/sessions
Content-Type: application/json





